/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx}",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#f0edef",
        "surface-tint": "#565e74",
        "primary-container": "#131b2e",
        "tertiary-fixed-dim": "#ffafd3",
        "surface-container-high": "#eae7e9",
        "surface-bright": "#fcf8fa",
        "tertiary-fixed": "#ffd8e7",
        "inverse-primary": "#bec6e0",
        primary: "#000000",
        "on-primary-fixed": "#131b2e",
        secondary: "#00668a",
        "on-secondary-container": "#004d6a",
        "on-primary-container": "#7c839b",
        background: "#fcf8fa",
        "tertiary-container": "#3d0026",
        "surface-variant": "#e4e2e4",
        "surface-dim": "#dcd9db",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#3d0026",
        "on-surface-variant": "#45464d",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#85145a",
        "outline-variant": "#c6c6cd",
        "on-secondary-fixed": "#001e2c",
        "on-tertiary-container": "#d3579a",
        "on-background": "#1b1b1d",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "secondary-fixed-dim": "#7bd0ff",
        "primary-fixed": "#dae2fd",
        "on-secondary-fixed-variant": "#004c69",
        "surface-container-low": "#f6f3f5",
        "inverse-on-surface": "#f3f0f2",
        "on-primary": "#ffffff",
        "inverse-surface": "#303032",
        "primary-fixed-dim": "#bec6e0",
        outline: "#76777d",
        "surface-container-highest": "#e4e2e4",
        tertiary: "#000000",
        "secondary-container": "#40c2fd",
        "on-surface": "#1b1b1d",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        surface: "#fcf8fa",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#c4e7ff",
      },
      fontFamily: {
        headline: ["Epilogue", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
